# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='价格')),
                ('critic', models.IntegerField(default=0, verbose_name='评论量')),
                ('sale', models.IntegerField(default=0, verbose_name='销售量')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='评论量')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'tb_goods',
            },
        ),
    ]
